### PR TITLE
Adds a CONTRIBUTING.md file.

### PR DESCRIPTION
**Pull request by Iamgoofball**
The contents of this file will show up in the description box of any PRs opened by default, like the commit descriptions usually do and potentially warn confused coders away from coding the suggestions as PRs and wasting effort.

### CODE REVIEW

**Comment by avilv** [comment]
limiting changes to bug fixes only ?
PR requests are just that 'requests' no need to limit them, you can either merge if you think its a good idea, close if you think its bad, or leave open till you think it fits, no hard feelings.

if a contributor takes the time to suggest AND implement that's not a bad thing,
some suggestions are rejected / postponed because they are not priority/take too long for too little gain, doesn't mean they are bad.

**Comment by Iamgoofball** [comment]
the guy who owns the repo has stated he does not want feature contributions via pull requests in various pull requests and the readme for the repo

**Comment by Iamgoofball** [comment]
@fcalife

**Comment by fcalife** [comment]
Contributions are proceeding fine through discord. Read the subreddit for more info: www.reddit.com/r/dotaimba

**Comment by Iamgoofball** [comment]
At the time of this PRs creation that was not the case.

**Pull request closed without merging**
