### PR TITLE
THE BUFF DOOM DESERVES

### PR DESCRIPTION
**Pull request by remisbest**
⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧⛧                                                                                                                                                      ⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥ **BUFF PLS**⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥
⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥⛥

### CODE REVIEW

**Comment by brandonsturgeon** [comment]
xd another great buff from another memelord!

I swear firetoad must get tired as hell with all of these PRs.

**Comment by remisbest** [comment]
not quite a meme, imo lazy doom is really not fun to play when your Q and R only matters at the end, firetodo can always merge this if he's weaker than I am saying

**Comment by brandonsturgeon** [comment]
FireT said he doesn't like feature requests here unless you post them in the reddit suggestion thread first. Not saying you haven't, just wanted to make sure you were aware of that.

Most PRs here are usually memes.

**Comment by fcalife** [comment]
lul

**Pull request closed without merging**
