### PR TITLE
Refactored some of the existing hero codes

### PR DESCRIPTION
**Pull request by lmk1988**
I am trying to lessen the lag that many other players experienced

### CODE REVIEW

**Comment by Shushishtok** [comment]
Your effort is welcome, but too bad you didn't ask us before you did it.
We're COMPLETELY rewriting all the existing heroes, changing abilities and converting them to lua based. Take a look at the PRs for Bounty Hunter and Centaur.

If you wish to help us rework those heroes your help will be immensely welcome.

**Comment by lmk1988** [comment]
😄 sorry about that, I was hoping to do minor optimization while the rewrites were taking place.
I am definitely happy if I could help to rework one of those heroes, though it will properly take a longer time for me since I do not have a full grasp of the API and structures yet.

May I know where I can help? Or I could just try to solve some reported bugs on reddit

**Comment by fcalife** [comment]
@lmk1988 join us on the development discord: https://discord.gg/QuVueK4

**Comment by lmk1988** [comment]
Oh i did haha i'm broccoli. Gonna close this then open another one just for refactoring pugna ward to use contants. Should be doing it later at night

**Comment by Shushishtok** [comment]
Closed then. :+1:

**Pull request closed without merging**
