### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by AtroCty**
I hope you have no big problems with this. :3

### CODE REVIEW

**Comment by brandonsturgeon** [comment]
This is fine. `.gitignore` is a useless waste of space anyway.

LGTM, let's get this merged.

**Comment by Iamgoofball** [comment]
Why would you remove the fucking .gitignore stop

**Comment by fcalife** [comment]
Added Blink boots to the main game

**Comment by fcalife** [comment]
we need to update this

thanks for the help though :thumbsup:

**Pull request closed without merging**
