### PR TITLE
Upgrade to v4 stat-collection, fix schema issues

### PR DESCRIPTION
**Pull request by jimmydorry**
Don't forget to drop in our two new panorama files. They go in your content folder.

https://github.com/GetDotaStats/stat-collection/tree/master/content/dota_addons/YOUR_ADDON/panorama

Make sure to test this as soon as you push it live. If there are any issues, comment out the require stat-collection line in your main lua file, and get back to us!

### CODE REVIEW

**Comment by fcalife** [comment]
merging manually

**Comment by jimmydorry** [comment]
Make sure to drop in the latest stat-collection version.

https://raw.githubusercontent.com/GetDotaStats/stat-collection/master/game/dota_addons/YOUR_ADDON/scripts/vscripts/statcollection/lib/statcollection.lua

:+1:

**Comment by jimmydorry** [comment]
Oh, and for heaven's sake, please double check the schema! You haven't had stats in forever over something as simple as having an old schemaID!

[Your schema contents](http://getdotastats.com/#s2__mod_schema?mid=74)
[Your schemaID](http://getdotastats.com/#s2__my__mods)

**Comment by fcalife** [comment]
done and done. Thank you!

2015-12-02 1:37 GMT-03:00 jimmydorry <notifications@github.com>:

> Oh, and for heaven's sake, please double check the schema! You haven't had
> stats in forever over something as simple as having an old schemaID!
>
> Your schema contents <http://getdotastats.com/#s2__mod_schema?mid=74>
> Your schemaID <http://getdotastats.com/#s2__my__mods>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fcalife/dota_imba/pull/43#issuecomment-161178327>.
>



-- 
Felipe Calife

**Pull request closed without merging**
