### PR TITLE
Break fix for all IMBA heroes

### PR DESCRIPTION
**Pull request by Shushishtok**
Silver Edge now has PassiveDisabled state. All relevant heroes' passives
are now disabled when on break. Also works on breaks for Doom's
Aghnaims.
Minimal testing for each hero on basic interactions, please notify me if
there are any troublesome interactions resulting from this.

### CODE REVIEW

**Comment by Shushishtok** [comment]
It seems like I mistakenly added the files for Lion and Skywrath Mage IMBA from previous pull requests. Please ignore those files.

**Comment by fcalife** [comment]
This one could simply be merged after solving some small conflicts, but I'd rather go through all the changes to understand them better.

Thank you very much for this! :)

**Comment by Shushishtok** [comment]
No problem, you're of course welcome to ask me if anything is unclear.

You welcome,
Shush

**Comment by fcalife** [comment]
deprecated since we're rewriting all heroes. I'll still use this as reference.

**Pull request closed without merging**
